### ISSUE TITLE
Script concatination

### ISSUE THREAD

**Issue by cromosom** [mzdr/web-boilerplate#1]
Hi Basti,

this boilerplate looks great! I'd like to test it and maybe use it for my own stuff. Do you plan on implementing script concatenation?

**Comment by mzdr** [comment]
Hi Tim! :grin: 

Sounds great, hope it serves you well! About the concatenation stuff: It kind of depends on what you are looking for. Right now every `*.js` file in `src/js` will land in `assets/scripts/`.

But any `*.js` file **inside a sub-directory** of `src/js` will be **ignored(!)**, unless you **require/import** it inside a `*.js` in `src/js`. Check the example I put there, maybe this will help you understand it.

So right now you can have a bunch of `*.js` files in a big sub-directory structure and they all will be bundled/concatenated to a single file **if** they are required/imported. 

Best regards from Zurich,
Basti :smile:

**Comment by cromosom** [comment]
Works like a charm!

Best wishes from Berlin :wink:
